package com.qinggan.canbus;

import android.os.Parcel;
import android.os.Parcelable;

import com.qinggan.canbus.plugs.DLNAManager;
import com.qinggan.canbus.plugs.SceneID;
import com.qinggan.canbus.plugs.VoiceActionID;

public enum VehicleStateAutoTest implements Parcelable {
    ENTER_DIAG_MODE(VoiceActionID.ACTION_VOICE_ONLINEVIDEO_QUERY),
    EXIT_DIAG_MODE(VoiceActionID.ACTION_VOICE_ONLINEVIDEO_PLAY_SOURCE),
    PDSN_READ_REQ(VoiceActionID.ACTION_VOICE_ONLINEVIDEO_CONTROL),
    PDSN_READ_RESP(VoiceActionID.ACTION_VOICE_CAR_REAR_DETECTION),
    PDSN_READ_RESP_NG(VoiceActionID.ACTION_VOICE_CAR_PHOTOGRAPH_CTRL),
    PDSN_WRITE_REQ(387),
    PDSN_WRITE_RESP(VoiceActionID.ACTION_VOICE_SYSTEM_CHAT),
    PDSN_WRITE_RESP_NG(VoiceActionID.ACTION_PLAY_SUBSCRIBE_ITEM),
    MBSN_READ_REQ(VoiceActionID.ACTION_FACTORY_CAMERA),
    MBSN_READ_RESP(VoiceActionID.ACTION_FACTORY_VISIT),
    MBSN_READ_RESP_NG(VoiceActionID.ACTION_SYSTEM_ACCOUNT_REFERENCE),
    MBSN_WRITE_REQ(VoiceActionID.ACTION_DIGITAL_MAN_CHANGE),
    MBSN_WRITE_RESP(VoiceActionID.ACTION_DIGITAL_MAN_QUERY),
    MBSN_WRITE_RESP_NG(VoiceActionID.ACTION_DIGITAL_MAN_DEFINE),
    WIFI_READ_REQ(VoiceActionID.ACTION_DIGITAL_MAN_PAY),
    WIFI_READ_RESP(VoiceActionID.ACTION_VOICE_AVATAR),
    WIFI_READ_SET_REQ(VoiceActionID.ACTION_FUSION_NEWS_INFO),
    WIFI_READ_SET_RESP(VoiceActionID.ACTION_FUSION_NEWS_CTRL),
    BT_READ_REQ(400),
    BT_READ_RESP(402),
    BT_READ_SET_REQ(403),
    BT_READ_SET_RESP(404),
    SN_READ_REQ(405),
    SN_READ_RESP(406),
    SN_READ_RESP_NG(407),
    OS_VERSION_READ_REQ(408),
    OS_VERSION_READ_RESP(409),
    VEHICLE_VERSION_READ_REQ(410),
    VEHICLE_VERSION_READ_RESP(411),
    SPEAK_VERSION_READ_REQ(412),
    SPEAK_VERSION_READ_RESP(413),
    A_VERSION_READ_REQ(VoiceActionID.ACTION_SOULMATE_CANCEL),
    A_VERSION_READ_RESP(VoiceActionID.ACTION_SOULMATE_IGNORE),
    B_VERSION_READ_REQ(VoiceActionID.ACTION_RADIO_PLAY),
    B_VERSION_READ_RESP(VoiceActionID.ACTION_CAR_MANUAL),
    MAP_PARTITION_READ_REQ(VoiceActionID.ACTION_VOICE_EMOTION_REPLY_DIVERSIFIED),
    MAP_PARTITION_READ_RESP(VoiceActionID.ACTION_VOICE_REJECT_RECOGNIZE),
    CURRENT_VOLUME_SET_REQ(VoiceActionID.ACTION_VOICE_PLAY_MUSIC),
    CURRENT_VOLUME_SET_RESP(VoiceActionID.ACTION_CAR_BONNET_CTRL),
    CURRENT_VOLUME_READ_REQ(VoiceActionID.ACTION_CHANGE_VOICE_SOUND),
    CURRENT_VOLUME_READ_RESP(VoiceActionID.ACTION_VOICE_CHAT_MODEL),
    SPEAK_VOLUME_SET(VoiceActionID.ACTION_SOUMATE_CUSTOM_SCENE),
    SPEAK_VOLUME_SET_RESP(VoiceActionID.ACTION_FUSION_NEWS_BULLET),
    SPEAK_VOLUME_REQ(VoiceActionID.ACTION_XIAOBING_START_CREATE),
    SPEAK_VOLUME_READ_RESP(VoiceActionID.ACTION_XIAOBING_CREATING),
    SYSTEM_TIME_READ_REQ(VoiceActionID.ACTION_XIAOBING_PAINTING_FINISHED_CREATE),
    SYSTEM_TIME_READ_RESP(VoiceActionID.ACTION_XIAOBING_CONFIRM_SHOW),
    SPEAK_RESOURCE_READ_REQ(430),
    SPEAK_RESOURCE_READ_RESP(4311),
    MAP_VERSION_READ_REQ(432),
    MAP_VERSION_READ_RESP(433),
    HIGH_TEMP_TIME_REQ(VoiceActionID.ACTION_XIAOBING_SHOW_MUSIC),
    HIGH_TEMP_TIME_RESP(VoiceActionID.ACTION_XIAOBING_POEM_FINISHED_CREATE),
    GPS_LOCATION_REQ(VoiceActionID.ACTION_DCS_RESTAURANT_ORDER_SUCCESS),
    GPS_LOCATION_RESP(VoiceActionID.ACTION_VOICE_START_LISTEN_FIRST),
    GPS_SATALITE_NUM_REQ(VoiceActionID.ACTION_CAR_SALE_INTRODUCTION),
    GPS_SATALITE_NUM_RESP(VoiceActionID.ACTION_INFO_COLLECT_QUESTION),
    IMSI_READ_REQ(440),
    IMSI_READ_RESP(VoiceActionID.ACTION_ROADBOOK_MEMORY_TODAY),
    IMSI_READ_RESP_NG(VoiceActionID.ACTION_ROADBOOK_MEMORY_THIS_MONTH),
    IMEI_READ_REQ(VoiceActionID.ACTION_ROADBOOK_MEMORY_THIS_YEAR),
    IMEI_READ_RESP(VoiceActionID.ACTION_ROADBOOK_ROAD_PHOTO),
    IMEI_READ_RESP_NG(VoiceActionID.ACTION_ROADBOOK_ROAD_VIDEO),
    TOX_ACCESS_STATUS_READ_REQ(VoiceActionID.ACTION_INTELCUBE_MOVE_FRONT),
    TOX_ACCESS_STATUS_READ_RESP(VoiceActionID.ACTION_INTELCUBE_MOVE_BACK),
    TOX_NETWORK_TYPE_READ_REQ(448),
    TOX_NETWORK_TYPE_READ_RESP(VoiceActionID.ACTION_INFO_COLLECT_COMPLETED),
    FM_FRE_SET_REQ(VoiceActionID.ACTION_DCS_CAR_VOICE_ALL_CONTROL),
    FM_FRE_SET_RESP(VoiceActionID.ACTION_DCS_HOTEL_CLARIFY),
    FM_FRE_READ_REQ(VoiceActionID.ACTION_DCS_FLIGHT_CLARIFY),
    FM_FRE_READ_RESP(VoiceActionID.ACTION_DCS_CAR_MASTER),
    AM_FRE_SET_REQ(VoiceActionID.ACTION_DCS_ME_TOO),
    AM_FRE_SET_RESP(VoiceActionID.ACTION_LAUNCH_KUWO_MUSIC),
    AM_FRE_READ_REQ(VoiceActionID.ACTION_IOT_SEARCH),
    AM_FRE_READ_RESP(VoiceActionID.ACTION_VOICE_VUI_RECORD_INTERRUPT),
    FM_SEEK_READ_REQ(VoiceActionID.ACTION_VOICE_ONE_TOUCH_CAR),
    FM_SEEK_READ_RESP(VoiceActionID.ACTION_VOICE_ONE_TOUCH_MUSIC),
    AM_SEEK_READ_REQ(VoiceActionID.ACTION_VOICE_ONE_TOUCH_NAVI),
    AM_SEEK_READ_RESP(VoiceActionID.ACTION_VOICE_ONE_TOUCH_SYSTEM),
    RSSI_SNR_READ_REQ(VoiceActionID.ACTION_VOICE_JOKE),
    RSSI_SNR_READ_RESP(VoiceActionID.ACTION_VOICE_NAVI_ITEM_SELECT),
    TOUCH_SCREEN_SET_REQ(VoiceActionID.ACTION_VOICE_ONLINE_MUSIC_PLAY),
    TOUCH_SCREEN_SET_RESP(VoiceActionID.ACTION_VOICE_DAILY_MUSIC_RECOMMENDED),
    LCD_LEVAL_SET_REQ(VoiceActionID.ACTION_DCS_PHONE_CONTACTS_CONTROL),
    LCD_LEVAL_SET_RESP(VoiceActionID.ACTION_VOICE_SYNC_CONTACT_SILENCE),
    LCD_MCU_READ_REQ(VoiceActionID.ACTION_VOICE_ADAS_NOA),
    LCD_MCU_READ_RESP(VoiceActionID.ACTION_VOICE_ADAS_LANE_CHANGE),
    LCD_BRIGHT_READ_REQ(VoiceActionID.ACTION_VOICE_ADAS_CRUISE_SPEED),
    LCD_BRIGHT_READ_RESP(VoiceActionID.ACTION_VOICE_ADAS_FOLLOW_DISTANCE),
    LCD_BRIGHT_SET_REQ(VoiceActionID.ACTION_VOICE_TEL_NO_ANSWER),
    LCD_BRIGHT_SET_RESP(VoiceActionID.ACTION_VOICE_TEL_CONTACTS),
    ENTER_FACTORY_VIEW_SET_REQ(VoiceActionID.ACTION_THUNDER_PLAYER_CONTROL),
    ENTER_FACTORY_VIEW_SET_RESP(VoiceActionID.ACTION_VOICE_NAVI_PASS_ITEM_SELECT),
    USB_TEST_READ_REQ(VoiceActionID.ACTION_VOICE_SCREEN_MODE_CONTROL),
    USB_TEST_READ_RESP(VoiceActionID.ACTION_OFFLINE_SPEAKER),
    AUTO_PLAY_READ_REQ(VoiceActionID.ACTION_ID_MAX_NUM),
    AUTO_PLAY_READ_RESP(479),
    DIRECT_ENTER_MAP_SET_REQ(480),
    DIRECT_ENTER_MAP_SET_RESP(481),
    CARPLAY_ACCESS_READ_REQ(482),
    CARPLAY_ACCESS_READ_RESP(483),
    RECODE_SET_REQ(484),
    RECODE_SET_RESP(485),
    PLATBACK_SET_REQ(486),
    PLATBACK_SET_RESP(487),
    FAN_SET_REQ(488),
    FAN_SET_RESP(489),
    SPEAK_ACC_TEST_SET_REQ(490),
    SPEAK_ACC_TEST_SET_RESP(491),
    FACTORT_RESET_SET_REQ(492),
    FACTORT_RESET_SET_RESP(493),
    USB_SPEED_WRITE_SET_REQ(494),
    USB_SPEED_WRITE_SET_RESP(495),
    USB_SPEED_READ_SET_REQ(496),
    USB_SPEED_READ_SET_RESP(497),
    MFI_READ_REQ(498),
    MFI_READ_RESP(499),
    MFI_READ_RESP_NG(500),
    QUICK_RENTER_SLEEP_SET_REQ(501),
    QUICK_RENTER_SLEEP_SET_RESP(DLNAManager.MEDIA_RENDER_GENA_EVENT_CMD_SET_MEDIA_PLAYINGSTATE),
    COOL_RESET_SET_REQ(DLNAManager.MEDIA_RENDER_GENA_EVENT_CMD_SET_MEDIA_URI),
    COOL_RESET_SET_RESP(DLNAManager.MEDIA_RENDER_GENA_EVENT_CMD_SET_MEDIA_DATA),
    ACC_STATUS_READ_REQ(DLNAManager.MEDIA_RENDER_GENA_EVENT_CMD_SET_MEDIA_MUTE),
    ACC_STATUS_READ_RESP(DLNAManager.MEDIA_RENDER_GENA_EVENT_CMD_SET_MEDIA_VOLUME),
    ACC_STATUS_SET_REQ(507),
    ACC_STATUS_SET_RESP(508),
    BT_STATUS_SET_REQ(509),
    BT_STATUS_SET_RESP(510),
    BT_STATUS_READ_REQ(511),
    BT_STATUS_READ_RESP(512),
    BT_ADDR_READ_REQ(513),
    BT_ADDR_READ_RESP(514),
    BT_ADDR_SET_REQ(SceneID.SCENE_QGXW_SELECT),
    BT_ADDR_SET_RESP(SceneID.SCENE_CALL),
    BT_ADDR_SCAN_REQ(SceneID.SCENE_RADIO),
    BT_ADDR_SCAN_RESP(SceneID.SCENE_PARKING),
    BT_ADDR_TEST_REQ(SceneID.SCENE_VEHICLE),
    BT_ADDR_TEST_RESP(SceneID.SCENE_POI),
    BT_ADDR_CLEAN_REQ(SceneID.SCENE_RESTAURANT),
    BT_ADDR_CLEAN_RESP(522),
    WIFI_STATUS_SET_REQ(523),
    WIFI_STATUS_SET_RESP(524),
    WIFI_STATUS_READ_REQ(525),
    WIFI_STATUS_READ_RESP(526),
    WIFI_ADDR_READ_REQ(527),
    WIFI_ADDR_READ_RESP(SceneID.SCENE_TOUR),
    WIFI_ADDR_SET_REQ(SceneID.SCENE_HOTEL),
    WIFI_ADDR_SET_RESP(SceneID.SCENE_MOVIE),
    WIFI_ADDR_SCAN_REQ(SceneID.SCENE_TRAIN),
    WIFI_ADDR_SCAN_RESP(SceneID.SCENE_TAKEOUT),
    GPS_LONGT_RESP(SceneID.SCENE_GASOIL),
    GPS_LATLT_RESP(SceneID.SCENE_ONLINE_VIDEO),
    GPS_ALTIT_RESP(SceneID.SCENE_WEATHER);

    public static final Parcelable.Creator<VehicleStateAutoTest> CREATOR = new Parcelable.Creator<VehicleStateAutoTest>() { // from class: com.qinggan.canbus.VehicleStateAutoTest.1
        /* JADX WARN: Can't rename method to resolve collision */
        @Override // android.os.Parcelable.Creator
        public VehicleStateAutoTest createFromParcel(Parcel source) {
            VehicleStateAutoTest state = VehicleStateAutoTest.values()[source.readInt()];
            state.value = source.readInt();
            return state;
        }

        /* JADX WARN: Can't rename method to resolve collision */
        @Override // android.os.Parcelable.Creator
        public VehicleStateAutoTest[] newArray(int size) {
            return new VehicleStateAutoTest[size];
        }
    };
    private int value;

    VehicleStateAutoTest(int value) {
        this.value = value;
    }

    public int getValue() {
        return this.value;
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    @Override // android.os.Parcelable
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(ordinal());
        dest.writeInt(this.value);
    }
}
